### ISSUE TITLE
[FEAT] Support logging in to a remote server through a proxy

### ISSUE THREAD

**Issue by kamusis** [vimiix/ssx#38]
In daily use, it is often necessary to log in to remote servers through a proxy server (such as a bastion host) using commands like the following: `ssh proxy_user_name@server_user_name@server_ip@proxy_ip -p proxy_port`. It would be very helpful if ssx could also support this.

**Comment by vimiix** [comment]
Thanks for your good idea. 

I implemented this in [this PR](https://github.com/vimiix/ssx/pull/39), but it may not be the exact behavior you expect. I added a new parameter `-J` (just like ssh behavior) to specify the hop chain address information, which supports multiple hops. It will be included in next release (maybe `v0.2.0`)

Usage samples:

```bash
ssx -J [proxy_user@]proxy_host[:proxy_port] [user@]host[:port]

# multilple hops:
ssx -J address1,address2,...  target_address
```
