### ISSUE TITLE
main.go rely on internal package import

### ISSUE THREAD

**Issue by Alopex4** [vimiix/ssx#7]
Hi Vimiix,
As a newbie `Go` developer, I found the `ssx/cmd/ssx/main.go` relies on `internal` import "github.com/vimiix/ssx/internal/cleaner".
In the `Goland` IDE it will cause an error until I modify it to "ssx/internal/cleaner". 

Do you consider to move the `cleaner` out of `internal` package or give it a hook function for public involve?

If there are any mistakes or omissions in what I have mentioned, please point them out. Thank you.

**Comment by vimiix** [comment]
@Alopex4  
`github.com/vimiix/ssx` is [module path](https://go.dev/ref/mod#glos-module-path) of current project, it is defined in [`go.mod`](https://github.com/vimiix/ssx/blob/main/go.mod). If your `go` version is greater than v1.11, it should be indexed correctly.

Of course, we also can consider moving `cleaner` into the `ssx` module.

**Comment by vimiix** [comment]
I have just moved the `cleaner` module into the `ssx` module, and I will release this change in next version.

commit: https://github.com/vimiix/ssx/commit/896735b5f6c92e8dee5009a1f2e2ccdb2e7583a5
